# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - run: npx cypress install
    - run: npx cypress run
    
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#     - name: Cypress run
#       uses: cypress-io/github-action@v2
#       with:
#         start: npm start
        
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ninjagame-backend:latest .
    - name: Push Image To DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ninjagame-backend:latest
